function write_outfile( dir, sim, params, X_coor, bit_err, Q )

  km=1000;
  str1='opt';
    if ( sim.en_read_ADS ==0 && sim.en_gen_ADS==0 )
        str1='matlab';
    end
    matfile =[ dir, str1,'_sb', ...
              num2str(sim.subband), '_',  ...
              num2str( 2^params.Nbpsc ),'QAM_', ...
              num2str(sim.precomp_en),'prec_', ...
              num2str(sim.cfotype),'cfo_', ...
              num2str(sim.mode),'mode_', ... 
              num2str(sim.FiberLength/80/km),'span_', ...
              num2str(sim.MAXSIM),'samples', ...
              ]; 
    dlmwrite( matfile, bit_err); 
    dlmwrite( matfile, Q,'-append'); 
    dlmwrite( matfile, X_coor ,'-append' ); 
    
end 